### ISSUE TITLE
Port the /para/html route

### ISSUE THREAD

**Issue by kod-kristoff** [spraakbanken/sblex-server#135]
# Task Description
- Port the `/para/html` route.

# Linked User Story (-ies)
- #90 

# Subtasks
- [ ] Add `/para/html` route.
- [ ] Handle no input.
- [ ] Handle bad input.
