### ISSUE TITLE
Return 404 for non-existent lid:s

### ISSUE THREAD

**Issue by kod-kristoff** [spraakbanken/sblex-server#143]
# Task Description
- Return 404 if lemma-id or saldo-id doesn't exist.
- Return informative response

# Linked User Story (-ies)
- #136 

# Subtasks
- [ ] Route `/lid/html`
- [ ] Route `/lid/graph`
- [ ] Route `/lid/protojs`
- [ ] Route `/lid/json`
- [ ] Route `/lid/xml`
